Start your notebook here:

<H1>Let's see the happienes of each country</h1>

Using a happiness index from each coutry we can see which countries are the happiest, how happy they are. But the quetion remains, what do we do about it?

In [3]:
#some code

# Install a pip package in the current Jupyter kernel
import sys
#!{sys.executable} -m pip install numpy

#import the libraries we'll be using

import pandas as pd
import numpy as np
import ast
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime
from dateutil.parser import parse

filepath = "../report_2018-2019.csv"
data = pd.read_csv(filepath,index_col = 0)
# index_col is just indicating that there is a row number stored in the first column

#view the head
data.head(10)

,Country or region,Year,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
Overall rank,,,,,,,,,
154,Afghanistan,2019,3.203,0.350,0.517,0.361,0.000,0.158,0.025
145,Afghanistan,2018,3.632,0.332,0.537,0.255,0.085,0.191,0.036
107,Albania,2019,4.719,0.947,0.848,0.874,0.383,0.178,0.027
112,Albania,2018,4.586,0.916,0.817,0.790,0.419,0.149,0.032
88,Algeria,2019,5.211,1.002,1.160,0.785,0.086,0.073,0.114
84,Algeria,2018,5.295,0.979,1.154,0.687,0.077,0.055,0.135
142,Angola,2018,3.795,0.730,1.125,0.269,0.000,0.079,0.061
47,Argentina,2019,6.086,1.092,1.432,0.881,0.471,0.066,0.050
29,Argentina,2018,6.388,1.073,1.468,0.744,0.570,0.062,0.054
116,Armenia,2019,4.559,0.850,1.055,0.815,0.283,0.095,0.064